name: dagster
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.10
  - pandas>=2.3
  - pip>=25.0
  - python=3.11
  - requests>=2.32
  - pip:
      - dagster==1.12.8
      - dagster-dbt==0.28.8
      - dagster-duckdb>=0.28.8
      - dagster-duckdb-pandas>=0.28.8
      - dagster-webserver>=1.12.8
      - dbt-bigquery>=1.11.0
      - dbt-core>=1.10.0,<1.11
      - duckdb>=1.4.3
      - meltano>=4.0.8
      - python-dotenv==1.2.1